/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Handle navigation requests with app shell
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')));

// Runtime caching for Cloudflare API calls
registerRoute(
	/^https:\/\/.*\.cloudflare\.com\/.*/i,
	new NetworkFirst({
		cacheName: 'cloudflare-cache',
		plugins: [
			new ExpirationPlugin({
				maxEntries: 50,
				maxAgeSeconds: 60 * 60 * 24 // 24 hours
			})
		]
	}),
	'GET'
);

// Handle skip waiting message
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting();
	}
});

// Push notification handler
self.addEventListener('push', (event) => {
	const data = event.data?.json() ?? {
		title: 'ThriveQuest',
		body: 'Time to check in!'
	};

	event.waitUntil(
		self.registration.showNotification(data.title, {
			body: data.body,
			icon: '/icon.svg',
			badge: '/icon.svg',
			tag: 'thrivequest-notification',
			requireInteraction: false
		})
	);
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
	event.notification.close();
	event.waitUntil(self.clients.openWindow('/'));
});
